# Generated by Django 5.2.4 on 2025-10-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='drawing_paths',
            field=models.JSONField(default=list),
        ),
    ]
