# Generated by Django 5.2.4 on 2025-09-22 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mindmap',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='mindmap',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
