# Generated by Django 5.2.4 on 2025-09-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mindmap_options_mindmap_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps', to='api.appuser'),
        ),
    ]
