# Generated by Django 5.2.4 on 2025-09-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='owner',
            field=models.ForeignKey(
                null=True, 
                blank=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='mindmaps', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name='mindmap',
            options={'ordering': ['-updated_at']},
        ),
    ]
