# Generated by Django 5.2.4 on 2025-09-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mindmap_owner'),
        ('api', '0004_auto_20250922_1326'),
    ]

    operations = [
    ]
